# Generated by Django 5.2.4 on 2025-08-16 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('can_add_book', 'Can add book (custom)'), ('can_change_book', 'Can change book (custom)'), ('can_delete_book', 'Can delete book (custom)'), ('canaddbook', 'Can add book (alias)'), ('canchangebook', 'Can change book (alias)'), ('candeletebook', 'Can delete book (alias)'))},
        ),
    ]
